[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_escrow = "FWroafTkQ2MVVEgaj3L3mvTkiyPuwJy3eYka4Pz6YWQG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jacksturtevant/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
